### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by vj-python** [deepklarity/jupyter-text2code#11]
Installed the extension in Google colab with the below code. 
import os
MYDIR = ("jupyter-text2code-master")
CHECK_FOLDER = os.path.isdir(MYDIR)
if not CHECK_FOLDER:
  !apt install unzip
  !wget -q https://github.com/deepklarity/jupyter-text2code/archive/master.zip
  !unzip -q master.zip
  !pip install /content/jupyter-text2code-master
  !apt-get install libomp-dev
  !apt-get install libomp-doc
!pwd

But when try to import the extension, get the below error
import sys
sys.path.insert(0,'../')
from mopp.mopp_serverextension import CodeGenerator

FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/dist-packages/mopp/mopp_serverextension/models/ner/vocab/lexemes.bin'

**Comment by dk-dsr** [comment]
This error is thrown due to incompatible spacy version. We have pinned the correct version now. Please uninstall the plugin by running: `pip uninstall mopp` Then take latest pull and follow the installation instructions from readme.
