### ISSUE TITLE
ERROR: No matching distribution found for faiss (from mopp==0.0.1)

### ISSUE THREAD

**Issue by Manikumar34** [deepklarity/jupyter-text2code#13]
Hi,
I'm getting the below error. please help  

ERROR: Could not find a version that satisfies the requirement faiss (from mopp==0.0.1) (from versions: none)
ERROR: No matching distribution found for faiss (from mopp==0.0.1)

**Comment by dk-crazydiv** [comment]
Hi. It looks like you're using windows machine #2. Current implementation is dependent on `faiss`, and we don't have a windows machine to test-on, so it might take some time before we add windows support.

**Comment by dk-dsr** [comment]
Currently windows not supported. You can use our docker images to use the extension.
