### ISSUE TITLE
Terminal icon not showing

### ISSUE THREAD

**Issue by geekjr** [deepklarity/jupyter-text2code#17]
I am installing on macOS Mojave CPU only. I have followed the cpu only instructions from the README. However, the terminal icon does not show up in jupyter. How do i fix this?

**Comment by bytesemantics** [comment]
You have to a) ensure you have installed jupyter nbextensions
b) register the mopp nbextension

**Comment by geekjr** [comment]
How do I register the mopp nbextension?

**Comment by geekjr** [comment]
You can enable the extension with `sudo -E jupyter nbextension enable mopp/main --sys-prefix`
