### ISSUE TITLE
Installation working but not Text2Code

### ISSUE THREAD

**Issue by Rundel12** [deepklarity/jupyter-text2code#20]
HI,

I really find the concept interesting however after installing I get the following error:

[W 19:07:57.734 NotebookApp] Error loading server extension jupyter_text2code.jupyter_text2code_serverextension
    Traceback (most recent call last):
      File "/Users/hicham/.local/lib/python3.7/site-packages/notebook/notebookapp.py", line 1942, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/opt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 728, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/opt/anaconda3/lib/python3.7/site-packages/jupyter_text2code/jupyter_text2code_serverextension/__init__.py", line 5, in <module>
        import faiss
      File "/opt/anaconda3/lib/python3.7/site-packages/faiss/__init__.py", line 19, in <module>
        from .swigfaiss import *
      File "/opt/anaconda3/lib/python3.7/site-packages/faiss/swigfaiss.py", line 649, in <module>
        class HammingComputer4(_object):
      File "/opt/anaconda3/lib/python3.7/site-packages/faiss/swigfaiss.py", line 655, in HammingComputer4
        __swig_setmethods__["a0"] = _swigfaiss.HammingComputer4_a0_set
    AttributeError: module 'faiss._swigfaiss' has no attribute 'HammingComputer4_a0_set'

Resulting in this error when trying to use the terminal on a notebook:

[W 19:08:00.061 NotebookApp] 404 GET /nbextensions/jupyter-text2code/icon.jpg (::1) 7.30ms referer=http://localhost:8888/tree

[W 19:08:21.215 NotebookApp] 404 GET /jupyter-text2code?query=help&dataframes_info=%27%7B%7D%27 (::1) 2.78ms referer=http://localhost:8888/notebooks/Untitled6.ipynb

Thanks for your help !

**Comment by Gunnika** [comment]
Hi @deepak-deepklarity 
I have a similar issue where whenever I try to run a command, I'm getting 404 GET error. 
The installation happened successfully. I'm using Ubuntu 20.04 on WSL2. 
Attaching a screenshot below, any leads will be appreciated! 
![get_error](https://user-images.githubusercontent.com/34855465/97093577-cd33ca80-166a-11eb-99a4-d152d9c7fc52.png)

**Comment by dk-dsr** [comment]
> HI,
> 
> I really find the concept interesting however after installing I get the following error:
> 
> [W 19:07:57.734 NotebookApp] Error loading server extension jupyter_text2code.jupyter_text2code_serverextension
> Traceback (most recent call last):
> File "/Users/hicham/.local/lib/python3.7/site-packages/notebook/notebookapp.py", line 1942, in init_server_extensions
> mod = importlib.import_module(modulename)
> File "/opt/anaconda3/lib/python3.7/importlib/**init**.py", line 127, in import_module
> return _bootstrap._gcd_import(name[level:], package, level)
> File "", line 1006, in _gcd_import
> File "", line 983, in _find_and_load
> File "", line 967, in _find_and_load_unlocked
> File "", line 677, in _load_unlocked
> File "", line 728, in exec_module
> File "", line 219, in _call_with_frames_removed
> File "/opt/anaconda3/lib/python3.7/site-packages/jupyter_text2code/jupyter_text2code_serverextension/**init**.py", line 5, in
> import faiss
> File "/opt/anaconda3/lib/python3.7/site-packages/faiss/**init**.py", line 19, in
> from .swigfaiss import *
> File "/opt/anaconda3/lib/python3.7/site-packages/faiss/swigfaiss.py", line 649, in
> class HammingComputer4(_object):
> File "/opt/anaconda3/lib/python3.7/site-packages/faiss/swigfaiss.py", line 655, in HammingComputer4
> **swig_setmethods**["a0"] = _swigfaiss.HammingComputer4_a0_set
> AttributeError: module 'faiss._swigfaiss' has no attribute 'HammingComputer4_a0_set'
> 
> Resulting in this error when trying to use the terminal on a notebook:
> 
> [W 19:08:00.061 NotebookApp] 404 GET /nbextensions/jupyter-text2code/icon.jpg (::1) 7.30ms referer=http://localhost:8888/tree
> 
> [W 19:08:21.215 NotebookApp] 404 GET /jupyter-text2code?query=help&dataframes_info=%27%7B%7D%27 (::1) 2.78ms referer=http://localhost:8888/notebooks/Untitled6.ipynb
> 
> Thanks for your help !

@Rundel12 Looks like you are installing on a machine without GPU. Please try these instructions: https://github.com/deepklarity/jupyter-text2code#cpu-only-install

**Comment by dk-dsr** [comment]
Hope you were able to use the extension by following CPU install instructions. Please reopen the issue if it's not resolved.
