### ISSUE TITLE
from jupyter-text2code==0.0.2

### ISSUE THREAD

**Issue by wwj-2017-1117** [deepklarity/jupyter-text2code#21]
ERROR: No matching distribution found for faiss (from jupyter-text2code==0.0.2)

**Comment by dk-crazydiv** [comment]
Windows isn't supported right now, as we decided to use a libary called `faiss` by [facebook research](https://github.com/facebookresearch/faiss). Tracking this in #2 and I'll try to commit an alternative branch which doesn't rely on faiss to perform intent matching.
