### ISSUE TITLE
Can anyone or author post a video on how to install this library?

### ISSUE THREAD

**Issue by nithinreddyy** [deepklarity/jupyter-text2code#23]
I've tried my level best to install this library and it installed but there is no snippet showing to enter the input. Can anyone or author of this library create a video on how to install this library from scratch?

**Comment by dk-dsr** [comment]
We will soon publish a docker image. Hopefully it will help you use the extension without any issues.

**Comment by dk-dsr** [comment]
We have published docker containers https://hub.docker.com/r/deepklarity/jupyter-text2code/
