### ISSUE TITLE
How to activate this jupyter nbextensions in google colab?

### ISSUE THREAD

**Issue by yugaljain1999** [deepklarity/jupyter-text2code#6]
I can't find path of nbextension specified in github repository..
![image](https://user-images.githubusercontent.com/32617984/92469070-d0294780-f1f1-11ea-8269-4af0c6f274e5.png)
@deepak-deepklarity @dk-crazydiv   please help!

**Comment by dk-crazydiv** [comment]
Hi,

I don't believe we could install and run a jupyter frontend+server extension in google-colab. If you find an example please share. 

As for trying out the demo and using it for your workflow, you could try accessing the code directly, but the experience wouldn't be that seamless. Example is available [here](https://github.com/deepklarity/jupyter-text2code/blob/master/notebooks/Code%20Generator.ipynb).
