### ISSUE TITLE
NotImplementedError: Cannot convert a symbolic Tensor (strided_slice_2:0) to a numpy array.

### ISSUE THREAD

**Issue by ahmedahmedov** [deepklarity/jupyter-text2code#7]
Hi, 
When playing around with the demo notebook, I received the above error after executing the following cell: 

cg.generate_code("import spacy")

What do you think is the solution? 

Operating system: MacOS
Python version: 3.7
Tensorflow version: 1.15.2

**Comment by dk-crazydiv** [comment]
Hi,
The code isn't tested for MacOS, but should work with `python3` on `tensorflow2` and `faiss-cpu`.

I am able to execute `cg.generate_code()` with these dependencies.
```
tensorflow==2.3.0
faiss-cpu==1.6.3
```
Please check if the issue still persists after these changes.

**Comment by dk-dsr** [comment]
Please reopen if issue not resolved.
